### ISSUE TITLE
Example server fails to start

### ISSUE THREAD

**Issue by penberg** [chiselstrike/chiselstore#39]
When attempting to start the example server, I trip over:

```
penberg@vonneumann chiselstore % cargo run --example gouged -- --id 1 --peers 2 3
    Updating crates.io index
   Compiling event-listener v2.5.3
   Compiling chiselstore v0.1.0 (/Users/penberg/src/chiselstrike/chiselstore/core)
   Compiling async-mutex v1.4.0
    Finished dev [unoptimized + debuginfo] target(s) in 6.63s
     Running `target/debug/examples/gouged --id 1 --peers 2 3`
RPC listening to 127.0.0.1:50001 ...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))', core/src/rpc.rs:55:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))', core/src/rpc.rs:55:52
```

I bisected the problem to 75ec0c75950499a91ef5dffcdc368cdc67924e38

**Comment by glommer** [comment]
I tried this commit and it worked for me. will investigate more

**Comment by glommer** [comment]
89a1a1fbd3eaaad23d386be8da01d9b4c6c3d653 OTOH breaks it.
